# Generated by Django 6.0.3 on 2026-03-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='roles',
        ),
    ]
