# Generated by Django 6.0.3 on 2026-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('WP_SUP', 'Workplace Supervisor'), ('AC_SUP', 'Academic Supervisor'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=10),
        ),
    ]
