# Generated by Django 6.0.3 on 2026-06-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('WP_SUP', 'Workplace Supervisor'), ('AC_SUP', 'Academic Supervisor'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=20),
        ),
    ]
