# Generated by Django 6.0.3 on 2026-03-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_identifier', models.CharField(blank=True, help_text='Temporary string / ID of the placement (to be replaced)', max_length=100)),
                ('evaluator_identifier', models.CharField(blank=True, help_text='Temporary string / username or ID of the evaluator (to be replaced)', max_length=100)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, help_text='When this evaluation was created')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('overall_comments', models.TextField(blank=True, help_text='General comments / recommendations')),
                ('total_score', models.FloatField(blank=True, help_text='Computed weighted total score', null=True)),
                ('final_grade', models.CharField(blank=True, help_text='A, B+, B, C, etc. (computed later)', max_length=5)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
