# Generated by Django 6.0.3 on 2026-04-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='week_number',
            field=models.PositiveIntegerField(),
        ),
    ]
