# Generated by Django 6.0.3 on 2026-05-01 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_weeklylog_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 14, 14, 31, 841958, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='week_end_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 1, 14, 14, 31, 841948, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='week_start_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 1, 14, 14, 31, 841930, tzinfo=datetime.timezone.utc)),
        ),
    ]
