# Generated by Django 6.0.3 on 2026-05-01 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_weeklylog_deadline_weeklylog_week_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 14, 15, 3, 7800, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='week_end_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 1, 14, 15, 3, 7794, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='week_start_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 1, 14, 15, 3, 7779, tzinfo=datetime.timezone.utc)),
        ),
    ]
