# Generated by Django 6.0.3 on 2026-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_alter_weeklylog_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='deadline',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='week_end_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='week_start_date',
            field=models.DateField(),
        ),
    ]
