# Generated by Django 6.0.3 on 2026-05-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_weeklylog_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylog',
            name='week_number',
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10),
        ),
    ]
