# Generated by Django 6.0.3 on 2026-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='final_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined final score (e.g. 40% AC + 60% WP)', max_digits=5, null=True),
        ),
    ]
